FROM node:20

WORKDIR /usr/src/app

# Copia somente package.json e yarn.lock
COPY package.json yarn.lock ./

# Instala dependências
RUN yarn install

# Copia o restante do código
COPY . .

# Instala nodemon global (opcional, ou coloque no package.json)

# Exposição da porta
EXPOSE 8000

# Comando de desenvolvimento
CMD ["yarn", "dev"]
