import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ContextsProvider from "@/context";

/* COMPONENTES */
import Alerts from "@/components/alerts";
import Header from '@/components/header';

/* ESTILO */
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col overflow-x-hidden`}
            >
                <ContextsProvider>
                    <Header/>
                    {children}
                    <Alerts/>
                </ContextsProvider>
            </body>
        </html>
    );
}
