name: CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instalar dependências (Backend)
        working-directory: backend
        run: yarn install

      - name: Rodar ESLint (Backend)
        working-directory: backend
        run: yarn run lint

      - name: Subindo os serviços
        working-directory: infra
        run: docker compose up db-tests redis-dev --build -d

      - name: Esperando os serviços um pouco
        run: sleep 15

      - name: Rodando os testes
        working-directory: backend
        run: yarn test:e2e

      - name: Build (Backend)
        working-directory: backend
        run: yarn run build

      - name: Derrubar containers
        if: always()
        run: docker compose -f e2e/docker-compose.e2e.yml down -v
